
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  encoding: unicode
  database: spree_with_extensions_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: spree_with_extensions_test
  min_messages: warning


production:
  <<: *default
url: <%= ENV['DATABASE_URL'] %>
